import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import { Toaster } from "sonner";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: "Trello",
  description: "Generated by create next app",
  icons: {
    icon: "/trello.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
